### ISSUE TITLE
NULL authors don't appear in structured comparison

### ISSUE THREAD

**Issue by tsakonase** [tsakonase/CoQAA#1]

**Comment by vegterj** [comment]
Example: for PUI 2013509457 an author exists with value ["Gabriela", "Wagner"] in Scopus and [null, null] in the Goldset; this presently returns no mismatches

**Comment by keerthi-els** [comment]
@vegterj

Believe for this bug issue is resolved.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/83961391/152292637-eca04cc6-c917-4a99-a5ed-39b4ec1859e4.png">
