### ISSUE TITLE
raw_affiliation_text should be treated as array with explode: true

### ISSUE THREAD

**Issue by vegterj** [tsakonase/CoQAA#11]

**Comment by keerthi-els** [comment]
It is working as expected after changing the configuration of raw affiliation in config file.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/83961391/152090926-cb7cdbbf-4743-48f9-99de-1995ecf229c5.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/83961391/152090889-1c264ddf-ba68-4fc3-8c90-0be146de85d3.png">
