### ISSUE TITLE
Returning empty list when both source and target arrays are different.

### ISSUE THREAD

**Issue by keerthi-els** [tsakonase/CoQAA#16]
@tsakonase @vegterj
Is below output expected ?

<img width="981" alt="image" src="https://user-images.githubusercontent.com/83961391/152291949-78797e8b-5307-44f7-8904-9dd2caf90f12.png">

**Comment by vegterj** [comment]
@keerthi-els yes, this is what I would expect here.

**Comment by tsakonase** [comment]
@keerthi-els Yes, this behaviour is expected
