### ISSUE TITLE
Including "collaboration" in yaml results in error: "int is not iterable"

### ISSUE THREAD

**Issue by tsakonase** [tsakonase/CoQAA#3]

**Comment by keerthi-els** [comment]
@tsakonase
For uneven number of empty strings in source and target, we are receiving "invalid split". Is this the right behaviour or should we fix it?

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/83961391/151919733-27594d01-eb4a-4f9a-85e7-7f617b68eb7c.png">

**Comment by tsakonase** [comment]
No, it should be an issue as well. Please report this as a separate issue

**Comment by tsakonase** [comment]
@keerthi-els No, it should be an issue as well. Please report this as a separate issue

**Comment by keerthi-els** [comment]
I will raise it as a separate issue !
